import exp from "constants";
import { Locale } from "./Locale";
import { ViewNames } from "./ViewNames";
//import { QuickFormDefinition } from "@eavfw/quickform-core";



export interface QuickFormDesignerState {
    activeView?: ViewNames;
    activeSlide?: string;
    activeQuestion?: string;
    [key: string]: string | undefined;
}

//export type QuickFormDesignerDefinition =  {
//    __designer: QuickFormDesignerState,
//    designerLocale?: Locale,
//    questions: {
//        [key: string]: {
//            /**
//             * If this question has been generated by some tool/framework and be used in designer if ediable.
//             */
//            generated?: boolean;

//            schemaName?: string;
//            displayName?: string;
//        }
//    }
//} & QuickFormDefinition;