import { QuickFormTokens } from "./quickFormTokensDefinition";

export const kbaQuickFormTokens: QuickFormTokens = {
    white: '#FFFFFF',
    black: '#000000',
    warning: '#FFA000',
    success: '#4CAF50',
    info: '#2196F3',

    primary: '#008000',
    primaryLighter: 'color-mix(in srgb, var(--primary) 80%, white)',
    secondary: '#008000',

    background: '#FAFAFA',
    onBackground: '#212121',

    onBackgroundDarker100: 'color-mix(in srgb, var(--on-background) 90%, black)',
    onBackgroundDarker200: 'color-mix(in srgb, var(--on-background) 80%, black)',
    onBackgroundDarker300: 'color-mix(in srgb, var(--on-background) 70%, black)',
    onBackgroundDarker400: 'color-mix(in srgb, var(--on-background) 60%, black)',
    onBackgroundDarker500: 'color-mix(in srgb, var(--on-background) 50%, black)',
    onBackgroundDarker600: 'color-mix(in srgb, var(--on-background) 40%, black)',
    onBackgroundDarker700: 'color-mix(in srgb, var(--on-background) 30%, black)',
    onBackgroundDarker800: 'color-mix(in srgb, var(--on-background) 20%, black)',
    onBackgroundDarker900: 'color-mix(in srgb, var(--on-background) 10%, black)',
    onBackgroundLighter: 'color-mix(in srgb, var(--on-background) 80%, white)',

    surface: '#EEEEEE',
    onSurface: '#212121',

    error: '#D32F2F',
    onError: '#FFFFFF',
    onErrorDarker100: 'color-mix(in srgb, var(--on-error) 90%, black)',
    onErrorDarker200: 'color-mix(in srgb, var(--on-error) 80%, black)',
    onErrorDarker300: 'color-mix(in srgb, var(--on-error) 70%, black)',
    onErrorDarker400: 'color-mix(in srgb, var(--on-error) 60%, black)',
    onErrorDarker500: 'color-mix(in srgb, var(--on-error) 50%, black)',
    onErrorDarker600: 'color-mix(in srgb, var(--on-error) 40%, black)',
    onErrorDarker700: 'color-mix(in srgb, var(--on-error) 30%, black)',
    onErrorDarker800: 'color-mix(in srgb, var(--on-error) 20%, black)',
    onErrorDarker900: 'color-mix(in srgb, var(--on-error) 10%, black)',

    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',

    fontFamily: 'Monaco, "Lucida Console", monospace',

    headlineFontSize: '2rem',
    paragraphFontSize: '1rem',
    paragraphMobileFontSize: '1rem',
    btnFontSize: '1.1rem',
    btnFontWeight: 600,
    btnEnterKeyTextFontSize: '1rem',
    multilineTextFontSize: '1.1rem',
    multilineTextMobileFontSize: '1rem',
    questionHeadlineFontSize: '1.4rem',
    questionParagraphFontSize: '1.2rem',
    questionNumberFontSize: '1.2rem',
    questionInputFontSize: "1.3rem",
    questionInputGap: "1.5rem",
    questionPlaceholderColor: '#757575',
    questionHeadlineFontWeight: 400,
    questionTopMargin: '15px',
    questionBottomMargin: '15px',
    questionBorderRadius: '15px',
    questionPadding: '0px',
    questionPaddingBottom: '15px',
    gap1: '0.5rem',
    gap2: '1rem',
    gap4: '2rem',
    disabledOpacity: 0.38,
    dividerOpacity: 0.12,
    lowEmphasisOpacity: 0.38,
    mediumEmphasisOpacity: 0.60,
    highEmphasisOpacity: 0.87,
};
